import{a as b,i as s,S as L}from"./assets/vendor-D0cagnvz.js";(function(){const a=document.createElement("link").relList;if(a&&a.supports&&a.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))o(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&o(i)}).observe(document,{childList:!0,subtree:!0});function n(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function o(t){if(t.ep)return;t.ep=!0;const r=n(t);fetch(t.href,r)}})();const w="47457730-c1e96e42c58ea46d8ed7b0f32",P="https://pixabay.com/api/";async function q(e,a=1,n=20){try{const o=await b.get(P,{params:{key:w,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:a,per_page:n}});return o.data.totalHits===0?(s.warning({message:"No images found. Please try another query!"}),null):o.data}catch(o){throw s.error({message:"Failed to fetch images. Please try again later!"}),new Error(o)}}function v(e,a){if(!e||e.length===0){a.innerHTML="";return}const n=e.map(({webformatURL:o,largeImageURL:t,tags:r,likes:i,views:m,comments:g,downloads:h})=>`
    <div class="photo-card">
      <a href="${t}" class="gallery-link">
        <img src="${o}" alt="${r}" loading="lazy" />
      </a>
      <div class="info">
        <p class="info-item"><b>Likes:</b> ${i}</p>
        <p class="info-item"><b>Views:</b> ${m}</p>
        <p class="info-item"><b>Comments:</b> ${g}</p>
        <p class="info-item"><b>Downloads:</b> ${h}</p>
      </div>
    </div>
  `).join("");a.innerHTML+=n}function S(e){e.innerHTML=""}const $=document.querySelector("#search-form"),f=document.querySelector(".gallery"),l=document.querySelector(".load-more"),d=document.querySelector("#loading");let c=1,y="";const u=15,E=new L(".gallery a",{captionsData:"alt",captionDelay:250});$.addEventListener("submit",async e=>{e.preventDefault();const a=e.target.querySelector("#search-input").value.trim();if(!a){s.warning({message:"Please enter a search query!"});return}y=a,c=1,S(f),l.style.display="none",await p()});l.addEventListener("click",async()=>{c+=1,await p()});async function p(){try{d.style.display="block";const e=await q(y,c,u);d.style.display="none",e&&e.hits.length>0&&(v(e.hits,f),E.refresh(),s.success({message:`Loaded ${e.hits.length} images!`}),c*u>=e.totalHits?(s.info({message:"We're sorry, but you've reached the end of search results."}),l.style.display="none"):l.style.display="block")}catch(e){s.error({message:"Failed to load images. Please try again later!"}),console.error(e)}}
//# sourceMappingURL=index.js.map
