import{a as q,i,S as v}from"./assets/vendor-D0cagnvz.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function s(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(t){if(t.ep)return;t.ep=!0;const o=s(t);fetch(t.href,o)}})();const P="47457730-c1e96e42c58ea46d8ed7b0f32",S="https://pixabay.com/api/";async function $(e,r=1,s=20){try{const a=await q.get(S,{params:{key:P,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:s}});return a.data.totalHits===0?(i.warning({message:"No images found. Please try another query!"}),null):a.data}catch(a){throw i.error({message:"Failed to fetch images. Please try again later!"}),new Error(a)}}function E(e,r){if(!e||e.length===0){r.innerHTML="";return}const s=e.map(({webformatURL:a,largeImageURL:t,tags:o,likes:n,views:g,comments:h,downloads:b,webformatWidth:w,webformatHeight:L})=>`
    <div class="photo-card">
      <a href="${t}" class="gallery-link">
        <img src="${a}" alt="${o}" loading="lazy" width="${w}" 
        height="${L}" />
      </a>
      <div class="info">
        <p class="info-item"><b>Likes:</b> ${n}</p>
        <p class="info-item"><b>Views:</b> ${g}</p>
        <p class="info-item"><b>Comments:</b> ${h}</p>
        <p class="info-item"><b>Downloads:</b> ${b}</p>
      </div>
    </div>
  `).join("");r.innerHTML+=s}function H(e){e.innerHTML=""}const O=document.querySelector("#search-form"),y=document.querySelector(".gallery"),l=document.querySelector(".load-more"),u=document.querySelector("#loading");let c=1,p="";const f=15;let d=!1;const I=new v(".gallery a",{captionsData:"alt",captionDelay:250});O.addEventListener("submit",async e=>{e.preventDefault();const r=e.target.querySelector("#search-input").value.trim();if(!r){i.warning({message:"Please enter a search query!"});return}p=r,c=1,H(y),l.style.display="none",await m()});l.addEventListener("click",async()=>{c+=1,await m()});async function m(){if(!d){d=!0;try{u.style.display="block";const e=await $(p,c,f);e&&e.hits.length>0&&(E(e.hits,y),I.refresh(),M(),c*f>=e.totalHits?(i.info({message:"We're sorry, but you've reached the end of search results."}),l.style.display="none"):l.style.display="block")}catch(e){i.error({message:"Failed to load images. Please try again later!"}),console.error(e)}finally{u.style.display="none",d=!1}}}function M(){var r,s;const e=((s=(r=document.querySelector(".gallery .photo-card"))==null?void 0:r.getBoundingClientRect())==null?void 0:s.height)||0;window.scrollBy({top:e*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
